### ISSUE TITLE
Create your own C# Doubly Linked List Data-Structure

### ISSUE THREAD

**Issue by Kerykeion7** [Kerykeion7/DataStructuresAndAlgorithms#11]
### First
- In the DataStructures.Lib project inside the "LinkedLists" folder create a class that will implement how a _Doubly Linked List_ data structure should work. 
- Name the class 'YourName'LinkedList.

Check [this](https://www.youtube.com/watch?v=RBSGKlAvoiM&feature=youtu.be&t=2103) for a greater understanding of Linked Lists.

### Next
- Create some XUnit Tests to check if your implementation is working correctly in the DataStructuresAndAlgorithms.Test project.
- Create a new test class for this in the **DataStructureTests/LinkedLists** folder and name it 'YourName'LinkedListTests.

There are a few example test available if needed in the test project as well as an example Linked List implementation in the DataStructures.Lib project.

**You do not have to be assigned for this issue, anyone can do this, as many times as you please.**

**Comment by computamike** [comment]
hi @Kerykeion7  - I had a go at a doubly linked  list.... I've done a pull request.. and as I'm typing this I just realised that I forgot to implement the ability to remove an item from the list.... I'll add that and re-update.  Sorry

**Comment by computamike** [comment]
hi @Kerykeion7 - I added a Remove method.
