### ISSUE TITLE
Create your own C# Binary Search Algorithm

### ISSUE THREAD

**Issue by Kerykeion7** [Kerykeion7/DataStructuresAndAlgorithms#22]
### First
- In the Algorithms.Lib project inside the **Searching/BinarySearches** folder create a class that will implement how a _BinarySearch_ algorithm should work. 
- Name the class 'YourName'BinarySearch.

Check [this](https://www.geeksforgeeks.org/binary-search/) for a greater understanding of the Binary Search algorithm.

### Next
- Create some XUnit Tests to check if your implementation is working correctly in the DataStructuresAndAlgorithms.Test project.
- Create a new test class for this in the **AlgorithmTests/Searching/BinarySearches** folder and name it 'YourName'BinarySearchTests.

There are a few example test available if needed in the test project as well as an example Binary Search implementation in the Algorithms.Lib project.

**You do not have to be assigned for this issue, anyone can do this, as many times as you please.**

**Comment by noakishere** [comment]
Hey can i take this one?
